# Generated by Django 3.0.5 on 2020-04-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dept',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='hostel',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
