# Generated by Django 3.0.5 on 2020-04-24 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20200424_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 19, 58, 50, 729735, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 19, 58, 50, 729226, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='parent_post',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
