# Generated by Django 3.0.5 on 2020-05-03 17:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0034_auto_20200430_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 17, 52, 30, 109524, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 17, 52, 30, 107823, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagger_id', models.CharField(default='1', max_length=10)),
                ('tag_type', models.CharField(default='post', max_length=10)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2020, 5, 3, 17, 52, 30, 111174, tzinfo=utc))),
                ('post_id', models.CharField(default='1', max_length=10)),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
