# Generated by Django 3.0.5 on 2020-05-03 18:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0036_auto_20200503_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 18, 20, 16, 598511, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 18, 20, 16, 597440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 18, 20, 16, 599613, tzinfo=utc)),
        ),
    ]
