# Generated by Django 3.0.5 on 2020-05-03 18:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_auto_20200503_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 18, 33, 21, 53187, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 18, 33, 21, 52122, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 18, 33, 21, 54259, tzinfo=utc)),
        ),
    ]
