# Generated by Django 3.0.5 on 2020-05-03 18:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0038_auto_20200504_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 18, 56, 40, 316334, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 18, 56, 40, 315955, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 3, 18, 56, 40, 317427, tzinfo=utc)),
        ),
    ]
